### ISSUE TITLE
Issue badge plugin not workingwith Redmine 4.1.0 docker

### ISSUE THREAD

**Issue by ji8812** [akiko-pusu/redmine_issue_badge#134]
Hello

It seems all the version of the plugin is not working with 4.x and above on docker

can you investigate

version 3.4.13 is workingfine

**Comment by akiko-pusu** [comment]
Hi, @ji8812 Thanks for trying my plugin.
Could you let me know more about your environment?

- Docker image that you use
  - Pulled image from DockerHub?
  - Image that build by yourself? (with using Dockerfile?)

**Comment by ji8812** [comment]
hello i use docker compose no docker file

plugin is outside the container mounted in a volume to the redmine

**Comment by akiko-pusu** [comment]
OK, could you show me the docker compose file?
And, could you give me some more detailed information?

> plugin not working

Above information is too little to support.
Are there any error information on your browser?
Any errors are recorded on your rails log?

**Comment by ji8812** [comment]
version: '3.1'
services:
  redmine:
    image: redmine
    container_name: 
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 2048M
    ports:
      - 8061:3000
    volumes:
      - /mnt/disk/tracker/plugins:/usr/src/redmine/plugins
      - /mnt/disk/tracker/themes:/usr/src/redmine/public/themes
      - /mnt/disk/tracker/vendor:/usr/src/redmine/vendor
      - /mnt/disk/tracker/config:/usr/src/redmine/config    
      - /mnt/disk/tracker/files_new:/usr/src/redmine/files
      #- /opt/mount/redmine/log:/opt/redmine/log
    environment:
      REDMINE_DB_MYSQL: 
      REDMINE_DB_PASSWORD:
      REDMINE_DB_USERNAME: 
      REDMINE_DB_DATABASE:
      REDMINE_DB_PORT: 
 

when i install put the plugin and rebuild i get error 500 internal error

**Comment by akiko-pusu** [comment]
>  i install put the plugin and rebuild i get error 500 internal error

I think you have to run rails redmine:plugis:migrate.
Please see your production.log.  You can get more detailed error information.

**Comment by ji8812** [comment]
hi

rails is in the container , i dont get error 500 with version 3.4.13 only 4.X

**Comment by akiko-pusu** [comment]
Thansk again. Above information is too little to support.
So I can't help any more.
Could you please attach at least a screenshot?
Also please send some production.log message.

Here is a common template to report bug. If you give me more detailed information,  I might support more effectively. 

## Summary


## Description


## Environment

These informations are greatly helpful to support quickly.
You can get these informations from Redmine's information page.
(E.g. http://example.com/admin/info)

- Redmine version
- Installed plugins
- Ruby version
- OS Platform
- Database (MariaDB, MySQL, PostgreSQL) and its version
- Rails Env


## Visual Proof / Screenshot

When reporting an application error, post the error stack trace that 
you should find in the **log file** (eg. log/production.log). 

Screen shot would be also helpful.


## Expected Results

## Actual Results

## Workaround

Please let me know if you have any workaround.

**Comment by ji8812** [comment]
Redmine version                4.1.0.stable
  Ruby version                   2.6.5-p114 (2019-10-01) [x86_64-linux]
  Rails version                  5.2.4.1
  Environment                    production


Redmine plugins:
  easy_gantt                     1.12
  redmine_agile                  1.5.3 with new patch for filter
  redmine_lightbox2              0.5.1




OS Platform debian 9
Database (MariaDB, MySQL, PostgreSQL) and its version - mysql 5.7
Rails Env

Visual Proof / Screenshot
When reporting an application error, post the error stack trace that
you should find in the log file (eg. log/production.log).

Screen shot would be also helpful.

Expected Results
working
![image](https://user-images.githubusercontent.com/63150368/78895663-4af20900-7a80-11ea-84bb-955f5c55d082.png)

Actual Results
Error 500 internal

**Comment by ji8812** [comment]
Redmine::PluginNotFound: Plugin not found. The directory for plugin redmine_issue_badge should be /usr/src/redmine/plugins/redmine_issue_badge.
redmine_1  | /usr/src/redmine/lib/redmine/plugin.rb:102:in `register'
redmine_1  | /usr/src/redmine/plugins/redmine_issue_badge-0.1.0/init.rb:39:in `<top (required)>'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
redmine_1  | /usr/src/redmine/lib/redmine/plugin.rb:181:in `block in load'
redmine_1  | /usr/src/redmine/lib/redmine/plugin.rb:172:in `each'
redmine_1  | /usr/src/redmine/lib/redmine/plugin.rb:172:in `load'
redmine_1  | /usr/src/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `block in load'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:663:in `block in load_config_initializer'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:662:in `load_config_initializer'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `each'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `block in <class:Engine>'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `each'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `tsort_each_child'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
redmine_1  | /usr/src/redmine/config/environment.rb:16:in `<top (required)>'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
redmine_1  | /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require_environment!'

**Comment by akiko-pusu** [comment]
Ok, above information is enough.

Then, please **see** README.

Each plugin's directory name must be the same to the name defined at init.rb.
So, you have to store my plugin as "redmine_issue_badge".

That's all.

Ref. https://github.com/akiko-pusu/redmine_issue_badge#plugin-installation

```
Plugin installation
Copy the plugin directory into the plugins directory. Please note that plugin's folder name should be "redmine_issue_badge". If changed, some migration task will be failed.
Do migration task.
e.g. rails redmine:plugins:migrate RAILS_ENV=production

(Re)Start Redmine. 
```

**Comment by ji8812** [comment]
done that as well can you please try

**Comment by akiko-pusu** [comment]
Did this solve the problem? I'm going to close this issue.

Please note: Not only my plugin but also other plugin's directory name must be the same to the name defined at ``init.rb``. If other plugin's directory does not follow the rule, an error will be remaining.

Also when you update some plugins, migration or bundle install will be required according to its README or release note.

**Comment by ji8812** [comment]
Hello

The problem is still here, as per documentation i just paste/clone the plugin in the directory and docker-compose up as i did for the other plugin.

Vers3.4.x is fine but not 4.x :(

So the issue isnot solve

**Comment by akiko-pusu** [comment]
If you store my plugin as ``redmine_issue_badge-0.1.0``, above error is still remaining.
yo have to remane the directory as ``redmine_issue_badge``.

Exp. /mnt/disk/tracker/plugins:/usr/src/redmine/plugins/redmine_issue_badge

After that,  docker-compose down and docker-compose up and look your production.log again.

Sorry I could not support without this logging information.

**Comment by ji8812** [comment]
hello

I did rename the plugin as you mention before

**Comment by ji8812** [comment]
even on a fresh install with just that plugin i get error 500 :(

**Comment by akiko-pusu** [comment]
Please give me your production.log. Error message is quite important to support.
Without this, I can't support and I'm going to close this issue.

If you can't provide more detailed info, I recommend you not to use my plugin.

**Comment by ji8812** [comment]
![image](https://user-images.githubusercontent.com/63150368/78991740-b1435e00-7b4a-11ea-98c4-c42f05ee2546.png)

**Comment by akiko-pusu** [comment]
> Redmine::PluginNotFound: Plugin not found. The directory for plugin redmine_issue_badge should be /usr/src/redmine/plugins/redmine_issue_badge.
redmine_1 | /usr/src/redmine/lib/redmine/plugin.rb:102:in register' redmine_1 | /usr/src/redmine/plugins/redmine_issue_badge-0.1.0/init.rb:39:in <top (required)>'


The above log shows that the plugin is located as "/usr/src/redmine/plugins/redmine_issue_badge-0.1.0/"

I think this depends on your environment.
**Docker volume doesn't seem to be syncing properly.**

You should store my plugin under /mnt/disk/tracker/plugins//redmine_issue_badge.
Not under /home/esokia/redmine/plugins/.

**Comment by ji8812** [comment]
yes but this is a test env to see your plugin alone

**Comment by akiko-pusu** [comment]
I say again. This is because you do not install the plugin correctly.

**Comment by ji8812** [comment]
ok can you show me how to do it on versi0n 4
